### ISSUE TITLE
Measures and other questions

### ISSUE THREAD

**Issue by cforce** [Surgo/redmine_reposearch#10]
Can u give a hint how mich percent of org data site is needed to keep the index.

Is "only" head revisions index are the complete history the way down.
If yes,
-  how can i search a revisions up or down to>?
  - where can i see which revision the search hit does link to?
- Are only "new commit" crawled and index or is it possible to recreate the index for ALL REVISIONS back to Revision1

What are the advantage or disadvantage of the two indexing methods wget or subversion hook? Is the complete repo indexed every time or only diffs?

**Comment by Surgo** [comment]
Hi, cforce.

Thanks for your reports.

> Is "only" head revisions index are the complete history the way down.

Yes. Its indexing newest codes.

> how can i search a revisions up or down to>?

Not support yet. 
But if support it, index file will become very very big, and take for long long time.

> Are only "new commit" crawled and index or is it possible to recreate the index for ALL REVISIONS back to Revision1
> 
> What are the advantage or disadvantage of the two indexing methods wget or subversion hook? Is the complete repo indexed every time or only diffs?

1st, a long time is necessary to making index file.
So I tried to minimize crawl. It use commit hook (subversion or other VCS).
If missing index file, try to indexing all files in a latest revision.
If already have index file, its crawl only diff.

Thanks,
Kosei.

**Comment by Surgo** [comment]
I try to support, multiple repositories, and branches :)
