### ISSUE TITLE
It couldn't access to "settings" of a project after an error.

### ISSUE THREAD

**Issue by maple** [Surgo/redmine_reposearch#11]
It couldn't access to "settings" of a project which reposerch module is available on after check_enabled in repoindexer_controller.rb had returned false.
1. access to redmine by using http://hogehoge + invalid key to make index, then Filter chain halted as [:check_enabled] rendered_or_redirected.
   log shows 'Access denied. Repository management WS is disabled or key is invalid.'.
2. click settings page.

After this, I have to reboot the  redmine...
Do you know some ideas?

the log is below.

ActionView::TemplateError (Missing host to link to! Please provide :host parameter or set default_url_options[:host]) on line #19 of app/views/projects/settings/_repository.html.erb:
16: <% button_disabled = true %>
17: <% if @repository %>
18: <%   button_disabled = ! @repository.class.scm_available %>
19: <%=    repository_field_tags(f, @repository)%>
20: <% end %>
21: </div>
22: 

```
(eval):21:in `root_url'
app/helpers/repositories_helper.rb:184:in `mercurial_field_tags'
app/helpers/repositories_helper.rb:123:in `send'
app/helpers/repositories_helper.rb:123:in `repository_field_tags'
app/views/projects/settings/_repository.html.erb:19
app/views/projects/settings/_repository.html.erb:1
app/views/common/_tabs.html.erb:24
```

自分の環境のせいかもしれませんが．．．

**Comment by Surgo** [comment]
Hi, maple.

I think its a same as this issue: http://www.redmine.org/issues/8556
This plugin call a `fetch_changesets` command before indexing.

So, you have to enable WS system and specify its key: http://www.redmine.org/projects/redmine/wiki/HowTo_setup_automatic_refresh_of_repositories_in_Redmine_on_commit

Regards,
Kosei.

**Comment by cforce** [comment]
Here the same .. and we exactly use the configuration from redmine.org http://www.redmine.org/projects/redmine/wiki/HowTo_setup_automatic_refresh_of_repositories_in_Redmine_on_commit

Indexing works and suddenly project settings don't works any longer , same error message as commented above .. than after a time it works again ..
This is very unstable..

**Comment by cforce** [comment]
We enable WS system and specify its key correctly. IT works but sadly also produces the error i mentioned above.
Did you track down cause already? 
At this state the plugin is making redmine highly unstable.

**Comment by Surgo** [comment]
Is `fetch_changesets` works without this plugin?

**Comment by cforce** [comment]
yep, we use advanced subversion interation, and redmine repository view  triggeres fetch_changesets by site render and by subversion post-commit hook.

**Comment by cforce** [comment]
Any more ideas, because chnaheset sync works perfectly.

**Comment by cforce** [comment]
Please fix the bugs. there are already two issues and 5 users reporrting it

https://github.com/Surgo/redmine_reposearch/issues/15
https://github.com/Surgo/redmine_reposearch/issues/11

**Comment by Surgo** [comment]
@maple @cforce 遅くなってしまい申し訳ありません。新しいバージョンを push しましたので、そちらで現象を確認してみてください。

**Comment by Surgo** [comment]
duplicate with #15

**Comment by maple** [comment]
ありがとうございます．ちょっといま忙しいのですが，時間を作って確認してあとで報告しますね．
