### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by schaarda** [Surgo/redmine_reposearch#13]
I'm using Redmine 1.3.0 and can't get this plugin to work for me. If I try to index a project, I get the following error:

Processing RepoindexerController#index (for 172.x.x.x at 2012-02-24 10:50:49) [GET]

NoMethodError (undefined method `check_enabled' for #<RepoindexerController:0x5d3bd00>):
  config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in`dispatch_cgi'

Rendering C:/Seu/Redmine/apps/redmine/public/500.html (500 Internal Server Error)

If I try to go to the reposearch page anyway, the following error occurs:

Processing ReposearchController#search (for 172.x.x.x at 2012-02-24 10:52:35) [GET]
  Parameters: {"action"=>"search", "id"=>"test", "controller"=>"reposearch"}

NoMethodError (undefined method `find_projects' for #<ReposearchController:0x6001650>):
  config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in`dispatch_cgi'

**Comment by Surgo** [comment]
Support new version.
