### ISSUE TITLE
integrate repo search into default search view

### ISSUE THREAD

**Issue by cforce** [Surgo/redmine_reposearch#14]
We don't line to have another own tab in project just for repo search.
There are several plugins which uintegrate themself into the standard search dialog vi a checkbox, someone can check so repository is searched as well.
Checkout  http://www.redmine.org/boards/3/topics/17306 which does that for example very well.

**Comment by cforce** [comment]
well hooks would be better than overwriting views, but i think ist better than another tab in project ..
https://github.com/xelkano/redmine_xapian/blob/master/app/views/search/index.rhtml

**Comment by cforce** [comment]
Would be great if this two plugin mirgrate btw.

**Comment by Surgo** [comment]
Add some SCM specific conditions like a repository, branches, and tags... So, I think its difficult :(
