### ISSUE TITLE
invalid multibyte char (US-ASCII)) please stay utf8 compatible!

### ISSUE THREAD

**Issue by cforce** [Surgo/redmine_reposearch#19]
raw_query = raw_query.gsub(/<THIS char is NOT UTf8>/

Is it a blank?

SyntaxError (/redmine-2.2/plugins/redmine_reposearch/app/controllers/reposearch_controller.rb:70: invalid multibyte char (US-ASCII)):
  org/jruby/RubyKernel.java:1019:in `require'
  activesupport (3.2.10) lib/active_support/dependencies.rb:251:in`require'
  activesupport (3.2.10) lib/active_support/dependencies.rb:236:in `load_dependency'
  activesupport (3.2.10) lib/active_support/dependencies.rb:251:in`require'
  activesupport (3.2.10) lib/active_support/dependencies.rb:359:in `require_or_load'
  activesupport (3.2.10) lib/active_support/dependencies.rb:502:in`load_missing_constant'
  activesupport (3.2.10) lib/active_support/dependencies.rb:192:in `const_missing'
  org/jruby/RubyArray.java:1612:in`each'
  activesupport (3.2.10) lib/active_support/dependencies.rb:190:in `const_missing'
  activesupport (3.2.10) lib/active_support/inflector/methods.rb:230:in`constantize'
  org/jruby/RubyArray.java:1612:in `each'
  activesupport (3.2.10) lib/active_support/inflector/methods.rb:229:in`constantize'
  activesupport (3.2.10) lib/active_support/dependencies.rb:554:in `get'
  actionpack (3.2.10) lib/action_dispatch/routing/route_set.rb:1:in`(root)'
  actionpack (3.2.10) lib/action_dispatch/routing/route_set.rb:69:in `controller_reference'
  actionpack (3.2.10) lib/action_dispatch/routing/route_set.rb:54:in`controller'
  actionpack (3.2.10) lib/action_dispatch/routing/route_set.rb:32:in `call'
  org/jruby/RubyArray.java:1612:in`each'
  journey (1.0.4) lib/journey/router.rb:68:in `call'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.10) lib/action_dispatch/routing/route_set.rb:601:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in`call'
  actionpack (3.2.10) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in`call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.10) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.10) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in`call'
  actionpack (3.2.10) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in`context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.10) lib/action_dispatch/middleware/cookies.rb:341:in`call'
  activerecord (3.2.10) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  actionpack (3.2.10) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  org/jruby/RubyBasicObject.java:1667:in`**send**'
  org/jruby/RubyKernel.java:2077:in `send'
  activesupport (3.2.10) lib/active_support/callbacks.rb:405:in`**run_callback'
  activesupport (3.2.10) lib/active_support/callbacks.rb:408:in `_run__398024564__call__21252486__callbacks'
  org/jruby/RubyBasicObject.java:1667:in`__send**'
  org/jruby/RubyKernel.java:2077:in `send'
  activesupport (3.2.10) lib/active_support/callbacks.rb:81:in`run_callbacks'
  activesupport (3.2.10) lib/active_support/callbacks.rb:390:in `_run_call_callbacks'
  actionpack (3.2.10) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.10) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.10) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.10) lib/rails/rack/logger.rb:32:in`call_app'
  railties (3.2.10) lib/rails/rack/logger.rb:16:in `call'
  activesupport (3.2.10) lib/active_support/tagged_logging.rb:22:in`tagged'
  railties (3.2.10) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.10) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.10) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  actionpack (3.2.10) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack (1.4.1) lib/rack/lock.rb:15:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.10) lib/rails/engine.rb:479:in`call'
  railties (3.2.10) lib/rails/application.rb:223:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in`call'
  railties (3.2.10) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.1) lib/rack/handler/webrick.rb:59:in`service'

**Comment by Surgo** [comment]
Yes it's blank.
Are you use ruby 1.9?
I'll add [magic comment](http://jp.rubyist.net/magazine/?0025-Ruby19_m17n#l18) for 1.9.

**Comment by Surgo** [comment]
Magic comments were added on 3555e672e60a19f8aa1f9af15d1e2758ce06a567.
Is it work?

**Comment by cforce** [comment]
yes jruby 1.7 with jruby 1.9
works now.
