### ISSUE TITLE
ディレクトリ以下の絞り込み機能

### ISSUE THREAD

**Issue by hiroponz** [Surgo/redmine_reposearch#6]
はじめまして、hiroponzと申します。

リポジトリの全文検索プラグインを以前から探していたので、早速使わせて頂きました。
少し使ってみての要望ですが、検索条件として特定のディレクトリ以下を指定できると便利だと思います。
Subversionでバージョン管理をしていて、trunkとリリースブランチというディレクトリ構造となっているのですが、
trunkのみを検索したり、あるリリースブランチのみを検索できると非常に助かります。

ちなみに、Redmineのリポジトリブラウザ画面上部に検索ボックスを表示して、表示中のディレクトリ以下を検索対象にできないか試行錯誤しましたが挫折しました。

**Comment by Surgo** [comment]
はじめまして。機能要望ありがとうございます。

なるほど。たしかにその機能は便利ですね。

Hyper Estraier にそういう機能があるか確認してみます。

**Comment by Surgo** [comment]
アップデートで、複数リポジトリに対応してみました。

例えば subversion で `svnadmin create /path/to/repo` で作成したリポジトリに`trunk`, `branches/*`, `tags/*` という運用を行っていた場合:
- `file:///path/to/repo/trunk/`
- `file:///path/to/repo/tags/v1.0.0`

等とリポジトリを複数追加してください。検索画面で選択できるようになります。

また、mercurial, git 等はブランチやタグを選択して検索できるようにしてみました。
