### ISSUE TITLE
NoMethodError in ReposearchController#search

### ISSUE THREAD

**Issue by ghost** [Surgo/redmine_reposearch#9]
After clicked on <i>RepoSearch</i> in project:
<b>undefined method `find_projects' for # ReposearchController:0x948d8d8</b>

Application Trace :

<pre>
C:/Program Files/Ruby187/app/Redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `send'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `evaluate_method'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:166:in `call'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/filters.rb:225:in `call'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/filters.rb:629:in `run_before_filters'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/filters.rb:615:in `call_filters'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `ms'
C:/Program Files/Ruby187/lib/ruby/1.8/benchmark.rb:308:in `realtime'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `ms'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/flash.rb:151:in `perform_action'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/base.rb:532:in `send'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/base.rb:532:in `process_without_filters'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/filters.rb:606:in `process'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/base.rb:391:in `process'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/base.rb:386:in `call'
C:/Program Files/Ruby187/app/Redmine/vendor/rails/actionpack/lib/action_controller/routing/route_set.rb:438:in `call'
</pre>

first init:
<b>MissingSourceFile in ReposearchController#search</b>

<pre>
 -> "no such file to load -- estraier"
</pre>

**Comment by Surgo** [comment]
Hi, reg-github.

This scripts use HyperEstraier for search. Do you install it?

http://fallabs.com/hyperestraier/index.html

Regards,
Kosei.

**Comment by ghost** [comment]
thanks for your reply, now it's work.
I tested on windows without script., / on the Debian with required components is ok

You need to place information of <b>requirements</b> for your plugin.

<i>все-таки как-то неудобно,</i> 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; но спасибо за плагин :)

**Comment by Surgo** [comment]
Hi, reg-github.

I place documentation here. -> https://github.com/Surgo/redmine_reposearch/wiki/Document

Thanks,
Kosei.
